# Generated by Django 5.1.7 on 2025-03-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_cyclone_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyclone',
            name='stage',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
